#!/bin/bash
$searchPath
echo "1. Decide Condition"
if [ $# -lt 1 ] 
then 
	export CSCOPE_DB=$PWD/cscope.out
	searchPath=.
else
	searchPath=$@
fi

echo "2. File Operation"
rm -rf cscope.files 
touch cscope.files

echo "3. Get Filelist"
for x in $searchPath
do
	find $x -name "*.h" -o -name "*.bas" -o -name "*.frm" -o -name "*.xml" -o -name "*.cls"  -o -name "*.rc" -o -name "*.hpp" -o -name "*.cc" -o -name "*.js" -o -name "*.c" -o -name "*.mk" -o -name "*.cpp" -o -name "*.java" -o -name "*.xml" -o -name "*.C" >> cscope.files
done

echo "4. Edit Filelist"
sed "s#^#$PWD/#g" -i cscope.files

echo "5. Generate the cscope-related file"
cscope -bkq -i cscope.files > /dev/null 2>&1

echo "6. Generate the ctag-related file"
ctags -h js cpp c C h hpp java cs -R $@ > /dev/null 2>&1

echo "7. Export Environment"
export CSCOPE_DB=$PWD/cscope.out

echo "8. END!!"
