#!/bin/bash
#echo "Ignore below condition:"
#echo ".jar"
#echo "?                  #SVN not revisioned, svn add needed."
#echo ".apk"
#echo ".conf"
#echo ".so"
#echo ".sh"
#echo "X                 #file link "
#echo "==========================================================================================================="

#svn st | grep -v "\.jar" | grep -v "\.apk" | grep -v "\.xml" |grep -v "?" | grep -v "\.conf" |  grep -v "\.so" | grep -v "\.sh" | grep -v "Performing" | grep -v "\<X\>" | grep -v "dest" | grep -v "/1"

svn st | egrep "\.java|\.cc|\.cpp|\.h|\.gypi|\.html"


#echo "==========================================================================================================="
